<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 24/11/2019
 * Time: 12:56
 */

namespace iplme\controllers;


use common\models\IpCourseWare;
use common\models\IpCourseWareDetail;
use common\widgets\PublicFunctionUnion;
use yii\web\Controller;
use Yii;

class CoursController extends Controller
{

    public $prix = '';

    public function actions()
    {

        $langue = Yii::$app->session['langue']?Yii::$app->session['langue']:'fr';

        if ($langue=='fr'){
            $this->prix = '';
        }else{
            $this->prix = '_zh';
        }

        $this->layout = 'main'.$this->prix;

        return parent::actions(); // TODO: Change the autogenerated stub

    }

    public function actionIndex(){
        $models = IpCourseWare::find()->all();
        return $this->render('index'.$this->prix,['models'=>$models]);
    }

    public function actionDetail($id){
        $courseWare = IpCourseWare::findOne(["id"=>$id]);
        IpCourseWareDetail::setPrix($id);
        $items = IpCourseWareDetail::find()->where(['wid'=>$id])->all();
        return $this->render('detail'.$this->prix,[
            'model'=>$courseWare,
            'items'=>$items
        ]);
    }
}
