<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 24/11/2019
 * Time: 15:08
 */

namespace iplme\controllers;

use common\models\IpContactMessage;
use common\models\IpProfessuer;
use common\widgets\PublicFunctionUnion;
use Yii;
use yii\helpers\Json;
use yii\web\Controller;

class EcoleController extends Controller
{


    public $prix = '';

    public function actions()
    {

        $langue = Yii::$app->session['langue']?Yii::$app->session['langue']:'fr';

        if ($langue=='fr'){
            $this->prix = '';
        }else{
            $this->prix = '_zh';
        }

        $this->layout = 'ecole'.$this->prix;

        return parent::actions(); // TODO: Change the autogenerated stub

    }

    public function actionIndex(){
        return $this->render('index'.$this->prix);
    }


    public function actionPresentation(){
        return $this->render('presentation'.$this->prix);
    }

    public function actionVision(){
        return $this->render('vision'.$this->prix);

    }

    public function actionCampus(){
        return $this->render('campus'.$this->prix);

    }

    public function actionProfesseur(){
        $datas = IpProfessuer::find()->where(['status'=>'1'])->all();
        return $this->render('professeur'.$this->prix,[
            'datas'=>$datas
        ]);

    }

    public function actionContact(){
        $this->layout = "main";
        $model = new IpContactMessage();
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
            $session = Yii::$app->session;
            $code = $session["code"];
            if ($code==$model->code){
                $model->status = 1;
                $model->ctime = PublicFunctionUnion::getTimeString();
                if ($model->save()){
                    $this->sendContactEmail($model->email,$model->message,$model->name);
                    return $this->redirect(['ecole/success']);
                }
            }else{
                $model->code = null;
            }


        }
        return $this->render('contact'.$this->prix,["model"=>$model]);
    }



    public function actionSuccess(){
        return $this->render('success');
    }


    public function sendContactEmail($email,$message,$nom){
        return Yii::$app
            ->mailer
            ->compose(
                ['html'=>'contact-vous-html','text'=>'contact-vous-text'],
                ['message'=>$message,"email"=>$email,"nom"=>$nom]
            )
            ->setTo($email)->setCc(["info@iplme.org"])
            ->setSubject("no_reply : Accusé de réception de votre message.")
            ->send();
    }



    public function actionGetcode()
    {
        if (Yii::$app->request->post()) {
            $email = Yii::$app->request->post("email");
            if ($email){
                $code = PublicFunctionUnion::generate_password(4);
                $session = Yii::$app->session;
                $session["code"] = $code;
                $this->sendCode($email,$code);
            }
            return Json::encode(["message"=>"Votre code a été envoyé à votre email！"]);
        }

    }

    private function sendCode($email,$code){
        return Yii::$app
            ->mailer
            ->compose(
                ['html'=>'code-html','text'=>'code-text'],
                ['code'=>$code]
            )->setTo($email)
            ->setSubject("no_reply : Votre code.")
            ->send();
    }

}
