<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 24/11/2019
 * Time: 17:50
 */

namespace iplme\controllers;
use yii\web\Controller;
use Yii;

class EntrepriseController extends Controller
{


    public $prix = '';

    public function actions()
    {

        $langue = Yii::$app->session['langue']?Yii::$app->session['langue']:'fr';

        if ($langue=='fr'){
            $this->prix = '';
        }else{
            $this->prix = '_zh';
        }

        $this->layout = 'entre'.$this->prix;

        return parent::actions(); // TODO: Change the autogenerated stub

    }


    public function actionIndex(){
        return $this->render('index'.$this->prix);
    }

    public function actionCooperation(){
        return $this->render('cooperation'.$this->prix);
    }



    public function actionTalent(){
        return $this->render('talent'.$this->prix);
    }


    public function actionSoutenez(){
        return $this->render('soutenez'.$this->prix);
    }
}
