<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 26/11/2019
 * Time: 14:54
 */

namespace iplme\controllers;


use common\models\Demander;
use common\models\dmander;
use common\models\IpDemanderFle;
use common\widgets\PublicFunctionUnion;
use yii\web\Controller;
use Yii;

class InscriptionController extends Controller
{


    public $prix = '';

    public function actions()
    {

        $langue = Yii::$app->session['langue']?Yii::$app->session['langue']:'fr';

        if ($langue=='fr'){
            $this->prix = '';
        }else{
            $this->prix = '_zh';
        }

        $this->layout = 'in'.$this->prix;

        return parent::actions(); // TODO: Change the autogenerated stub

    }



    public function actionIndex(){
        return $this->render('index'.$this->prix);
    }

    public function actionBba(){
        $model = new Demander();
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
            //save
            $model->ctime = PublicFunctionUnion::getTimeString();
            $model->type = 1;
            $model->status = 0;
            if($model->save()){
                $this->sendEmail($model->email,$model);
                return $this->redirect('index.php?r=site');
            }

        }
        return $this->render('bba'.$this->prix,[
            'model'=>$model
        ]);
    }

    public function actionMba(){
        $model = new Demander();
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
            //save
            $model->ctime = PublicFunctionUnion::getTimeString();
            $model->type = 2;
            $model->status = 0;
            if($model->save()){
                $this->sendEmail($model->email,$model);
                return $this->redirect('index.php?r=site');
            }
        }
        return $this->render('mba'.$this->prix,[
            'model'=>$model
        ]);
    }

    public function actionDba(){
        $model = new Demander();
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){

            $model->ctime = PublicFunctionUnion::getTimeString();
            $model->type = 3;
            $model->status = 0;
            //save
            if($model->save()){
                $this->sendEmail($model->email,$model);
                return $this->redirect('index.php?r=site');
            }
        }
        return $this->render('dba'.$this->prix,[
            'model'=>$model
        ]);
    }

    public function actionCours_en_ligne(){
        $model = new Demander();
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){

            $model->ctime = PublicFunctionUnion::getTimeString();
            $model->type = 4;
            $model->status = 0;
            //save
            if($model->save()){
                $this->sendEmail($model->email,$model);
                return $this->redirect('index.php?r=site');
            }
        }
        return $this->render('cours_en_linge'.$this->prix,[
            'model'=>$model
        ]);
    }


    public function actionInscription(){
        return $this->render('inscription');
    }

    public function actionFle(){

        $model = new IpDemanderFle();
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){

            $model->ctime = PublicFunctionUnion::getTimeString();
            $model->status = 0;
            //save
            if($model->save()){
                $this->sendEmailFle($model->email,$model);
                return $this->redirect('index.php?r=site');
            }
        }
        return $this->render('fle'.$this->prix,[
            'model'=>$model
        ]);
    }



    public  function sendEmail($email,$model){
        /* @var $user User */

        return Yii::$app
            ->mailer
            ->compose(
                ['html' => 'inscription-html', 'text' => 'inscription-text'],
                ['model'=>$model]
            )
            ->setTo($email)->setCc(["info@iplme.org"])
            ->setSubject('Inscription en ligne' )
            ->send();

    }


    public function sendEmailFle($email,$model){
        return Yii::$app
            ->mailer
            ->compose(
                ['html'=>'inscription-fle-html','text'=>'inscription-fle-text'],
                ['model'=>$model]
            )->setTo($email)->setCc(['info@iplme.org'])
            ->setSubject('no_reply Inscription fle en ligne')
            ->send();
    }





}
