<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 03/12/2019
 * Time: 20:16
 */

namespace iplme\controllers;

use Yii;
use yii\web\Controller;

class ProgrameController extends Controller
{



    public $prix = '';
    public $langue;

    public function actions()
    {

        $this->langue = Yii::$app->session['langue']?Yii::$app->session['langue']:'fr';

        if ($this->langue=='fr'){
            $this->prix = '';
        }else{
            $this->prix = '_zh';
        }

        $this->layout = 'main'.$this->prix;

        return parent::actions(); // TODO: Change the autogenerated stub

    }


    public function actionBba(){
        $this->layout = "programe".$this->prix;
        return $this->render('bba'.$this->prix);
    }


    public function actionMba(){
        $this->layout = "programe".$this->prix;

        return $this->render('mba'.$this->prix);
    }

    public function actionDba(){
        return $this->render('dba'.$this->prix);
    }


    public function actionStage(){
        return $this->render('stage'.$this->prix);
    }


    public function actionFle(){
        return $this->render('fle'.$this->prix);
    }


    public function actionPrepa(){
        return $this->render('prepa'.$this->prix);
    }


    public function actionEte(){
        return $this->render('ete'.$this->prix);
    }


    public function actionGymnase(){
        return $this->render('gymnase'.$this->prix);
    }


    public function actionCvec(){
        return $this->render('cvec'.$this->prix);
    }


    public function actionMarketing(){
        $this->layout = "programe".$this->prix;
        return $this->render('marketing'.$this->prix);
    }


    public function actionLogistique(){
        $this->layout = "programe".$this->prix;
        return $this->render('logistique'.$this->prix);
    }


    public function actionManagement(){
        $this->layout = "programe".$this->prix;
        return $this->render('management'.$this->prix);
    }

    public function actionTourisme(){
        $this->layout = "programe".$this->prix;
        return $this->render('tourisme'.$this->prix);
    }


    public function actionArt(){
        $this->layout = "programe".$this->prix;
        return $this->render('art'.$this->prix);
    }

    public function actionCommerce(){
        if ($this->langue=='zh'){
            return $this->render('commerce');
        }else{
            return $this->redirect('https://fr.calameo.com/read/005197759d74c1af9dfd7');
        }
    }

    public function actionCinema(){
        return $this->redirect("http://www.isiac.fr");
    }
}
