<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 25/11/2019
 * Time: 14:34
 */

namespace iplme\controllers;

use common\models\IpProfessuer;
use common\models\IpVieStudent;
use common\widgets\PublicFunctionUnion;
use Yii;
use yii\web\Controller;
use yii\data\Pagination;

class VieController extends Controller
{


    public $prix = '';

    public function actions()
    {

        $langue = Yii::$app->session['langue']?Yii::$app->session['langue']:'fr';

        if ($langue=='fr'){
            $this->prix = '';
        }else{
            $this->prix = '_zh';
        }

        $this->layout = 'vie'.$this->prix;

        return parent::actions(); // TODO: Change the autogenerated stub

    }


    public function actionIndex(){

        $query = IpVieStudent::find("status>0")->orderBy("status desc");
        $count = $query->count();
        $pagination = new Pagination(['totalCount' => $count]);
        $pagination->setPageSize(12);
        $datas = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index'.$this->prix,[
            'datas'=>$datas,
            'pagination'=>$pagination
        ]);
    }


    public function actionAssociation(){
        return $this->render('association'.$this->prix);
    }


    public function actionVie(){
        return $this->render('vie'.$this->prix);
    }


    public function actionDetail($id){
        $item = IpVieStudent::findOne(["id"=>$id]);
        return $this->render('detail',['item'=>$item]);
    }


    public function actionGymnase(){
        return $this->render('gymnase'.$this->prix);
    }

}
