<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 23/05/2019
 * Time: 18:01
 */

namespace admin\controllers;

use admin\models\AdminAccessControl;
use common\models\Admin;
use common\models\searchForm\AdminSearchForm;
use common\widgets\PublicFunctionUnion;
use yii\web\Controller;
use yii\filters\AccessControl;
use Yii;


class AdminController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','delete_admin','update_admin','create_admin'],
                        'allow' => true,
                        'matchCallback'=>function(){
                            return AdminAccessControl::getIsSuperAdmin();
                        }
                    ],
                    [
                        'actions' => ['update'],
                        'allow' => true,
                        'matchCallback'=>function(){
                            return true;
                        }
                    ],
                ],
            ],
        ];
    }



    public $layout = "admin";


    public function actions()
    {
        if (AdminAccessControl::getIsStudent()){
            $this->layout = "student";
        }else if (AdminAccessControl::getIsProfesseur()){
            $this->layout = "professeur";
        }
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){

        $model = new AdminSearchForm();
        $dataProvider = $model->search(Yii::$app->request->queryParams);

        return $this->render('index',[
            'dataProvider'=>$dataProvider,
            'searchModel'=>$model
        ]);

    }

    public function actionCreate_admin(){
        $model = new Admin();
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
            $model->setPassword($model->password);
            $model->ctime = PublicFunctionUnion::getTimeString();
            if ($model->save()){
                return $this->redirect('index.php?r=admin/index');
            }
        }

        return $this->render('createAdmin',[
            'model'=>$model
        ]);
    }

    public function actionDelete_admin($id){

        $model = Admin::findOne(["id"=>$id]);
        $model->delete();

        return $this->redirect("index.php?r=admin/index");
    }



    public function actionUpdate_admin($id){
        $model = Admin::findOne(["id"=>$id]);
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
            if ($model->save()){
                return $this->redirect("index.php?r=admin/index");
            }
        }

        return $this->render("updateAdmin",[
            "model"=>$model
        ]);

    }


    public function actionUpdate(){
        $id = Yii::$app->user->getId();
        $model = Admin::findOne(['id'=>$id]);
        if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
            if ($model->save()){
                if (AdminAccessControl::getIsStudent()){
                    return $this->render(["site/index"]);
                }else{
                    return $this->redirect("index.php?r=admin/index");
                }
            }
        }

        return $this->render("updatePassword",[
            "model"=>$model
        ]);
    }


    public function actionStudents(){
        return $this->render('students');
    }

    public function actionContact(){
        return $this->render('contact');
    }
}
