<?php
/**
 * Created by PhpStorm.
 * User: 37vip
 * Date: 11/12/2019
 * Time: 17:25
 */

namespace admin\controllers;


use admin\models\AdminAccessControl;
use common\models\Admin;
use common\models\Demander;
use common\models\IpDemanderFle;
use common\models\searchForm\DemanderSearchForm;
use common\models\searchForm\FleDemanderSearchForm;
use common\widgets\PublicFunctionUnion;
use yii\web\Controller;
use Yii;
use yii\filters\AccessControl;

class DemanderController extends Controller
{
    public $layout = "admin";


    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'index','delete_demander','update_demander','create_demander',
                            'fle','delete_demander_fle','update_demander_fle',
                            'create_demander_fle'
                        ],
                        'allow' => true,
                        'matchCallback'=>function(){
                            return AdminAccessControl::getIsSuperAdmin();
                        }
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        if (AdminAccessControl::getIsStudent()){
            $this->layout = "student";
        }else if (AdminAccessControl::getIsProfesseur()){
            $this->layout = "professeur";
        }
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){

        $searchModel = new DemanderSearchForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index',[
            'searchModel'=>$searchModel,
            'dataProvider'=>$dataProvider
        ]);
    }


    public function actionDelete_demander($id){
        if ($id){
            $model = Demander::findOne(['id'=>$id]);
            if ($model){
                $model->delete();
            }
        }
        return $this->redirect('index.php?r=demander/index');
    }


    public function actionUpdate_demander($id){
        if ($id){
            $model = Demander::findOne(['id'=>$id]);
            if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
                if ($model->save()){
                    return $this->redirect("index.php?r=demander/index");
                }
            }

            return $this->render("updateDemander",[
                "model"=>$model
            ]);
        }
        return $this->redirect('index.php?r=demander/index');
    }

    //TODO ADD INFOMATION NOTICE
    public function actionCreate_demander($id){
        if ($id){
            $model = Demander::findOne(['id'=>$id]);
            $user = Admin::findOne(['email'=>$model->email]);
            if ($user){
                $user->password = "non change";
                $this->sendEmail($user->email,$user);
                $model->uid = $user->getId();
                $model->status = 1;
                $model->save();
                if ($model->errors)
                    PublicFunctionUnion::printData($model->errors);
                return $this->redirect('index.php?r=demander/index');
            }else{
                $password = PublicFunctionUnion::generate_password();
                $userNew = new Admin();
                $userNew->email = $model->email;
                $userNew->types = Admin::USER_STUDENT;
                $userNew->name = $model->name;
                $userNew->display_name = $model->firstname;
                $userNew->permission = 1;
                $userNew->block = 0;
                $userNew->setPassword($password);
                $userNew->ctime = PublicFunctionUnion::getTimeString();
                $model->status = 1;
                if ($userNew->save()){
                    $model->uid = $userNew->getId();
                    $model->save();
                    $userNew->password = $password;
                    $this->sendEmail($userNew->email,$userNew);
                    return $this->redirect('index.php?r=demander/index');
                }

                return $this->redirect('index.php?r=demander/index');
            }
        }
    }





    public  function sendEmail($email,$model){
        /* @var $user User */

        return Yii::$app
            ->mailer
            ->compose(
                ['html' => 'signup-html', 'text' => 'signup-text'],
                ['model'=>$model]
            )
            ->setTo($email)
            ->setSubject("no_reply:Votre demande est bien envoyée et nous y répondrons le plus vite possible.")
            ->send();

    }


    public function actionFle(){
        $searchModel = new FleDemanderSearchForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('fle',[
            'searchModel'=>$searchModel,
            'dataProvider'=>$dataProvider
        ]);
    }


    public function actionDelete_demander_fle($id){

         if ($id){
             $fle = IpDemanderFle::findOne(['id'=>$id]);
             if ($fle){
                 $fle->delete();
             }
         }
        return $this->redirect('index.php?r=demander/fle');
    }


    public function actionUpdate_demander_fle($id){

        if ($id){
            $model = IpDemanderFle::findOne(['id'=>$id]);
            if (Yii::$app->request->post()&&$model->load(Yii::$app->request->post())){
                if ($model->save()){
                    return $this->redirect("index.php?r=demander/fle");
                }
            }

            return $this->render("update_demander_fle",[
                "model"=>$model
            ]);
        }
        return $this->redirect('index.php?r=demander/fle');
    }


    public function actionCreate_demander_fle($id){
        if ($id){
            $model = IpDemanderFle::findOne(['id'=>$id]);
            $user = Admin::findOne(['email'=>$model->email]);
            if ($user){
                $user->password = "non change";
                $this->sendEmail($user->email,$user);
                $model->uid = $user->getId();
                $model->status = 1;
                $model->save();
                if ($model->errors)
                    PublicFunctionUnion::printData($model->errors);
                $updateUser = Admin::findOne(["id"=>$user->id]);
                $updateUser->types = 3;
                $updateUser->save();
                return $this->redirect('index.php?r=demander/fle');
            }else{
                $password = PublicFunctionUnion::generate_password();
                $userNew = new Admin();
                $userNew->email = $model->email;
                $userNew->types = 3;
                $userNew->name = $model->name;
                $userNew->display_name = $model->firstname;
                $userNew->permission = 1;
                $userNew->block = 0;
                $userNew->setPassword($password);
                $userNew->ctime = PublicFunctionUnion::getTimeString();
                $model->status = 1;
                if ($userNew->save()){
                    $model->uid = $userNew->getId();
                    $model->save();
                    $userNew->password = $password;
                    $this->sendEmail($userNew->email,$userNew);
                    return $this->redirect('index.php?r=demander/fle');
                }

                return $this->redirect('index.php?r=demander/fle');
            }
        }
    }
}
